---
Name: mosaic-config
---

FileField:
  extensions:
    - MosaicFileFieldExtension

Image:
  extensions:
    - MosaicImageExtension

DropdownField:
  extensions:
    - MosaicDropdownFieldExtension

TextareaField:
  extensions:
    - MosaicTextareaFieldExtension