---
Name: mosaic-config
After:
  - '#dropzone'
---

ContentController:
  extensions:
    - MosaicContentControllerExtension

FileField:
  extensions:
    - MosaicFileFieldExtension

Image:
  extensions:
    - MosaicImageExtension

DropdownField:
  extensions:
    - MosaicDropdownFieldExtension

TextareaField:
  extensions:
    - MosaicTextareaFieldExtension

FileAttachmentField:
  module_scripts_dir: '/mosaic/js/widgets/dropzone/'
  dropzone_script_file: '/vendor/crackerjackdigital/dropzone/dist/dropzone.js'
  dropzone_config_file: '/mosaic/js/widgets/dropzone/dropzone_config.json'
