---
Name: mosaic-requirements
---
MosaicModule:
  script_types:
    js: true
    css: true
    jst: true
  combine:
    js: false
    css: true
  requirements:
    block:
      - '/framework/thirdparty/jquery/*'
    before:
      components/jquery/jquery.js: true
      components/modernizr/modernizr-built.js: true
      components/ckeditor/ckeditor.js: true
    after:
      components/masonry/masonry-built.js: true
      components/lodash/lodash-built.js: true
      components/postal.js/postal.js-built.js: true
      components/fotorama/fotorama-built.js: true
      components/select2/select2-built.js: true
      components/infinite-ajax-scroll/infinite-ajax-scroll-built.js: true
      js/mosaic.js: true
      js/components/postal.js: true
      js/components/ias.js: true
      js/components/masonry.js: true
      js/components/endless.js: true
      js/message-bus.js: true
      js/widgets/sidebar.js: true
      js/widgets/expando.js: true
      js/widgets/list.js: true
      js/widgets/endless.js: true
      js/widgets/tabbar.js: true
      js/widgets/actionmenu.js: true
      js/widgets/select2field.js: true
      js/widgets/ckeditor.js: true
      js/widgets/confirmedpasswordfield.js: true
      js/widgets/postable.js: true
      js/widgets/modal.js: true


