---
Name: mosaic-requirements
---
MosaicApplication:
  script_types:
    js: true
    css: true
    jst: true
  combine:
    js: false
    css: true
    jst: false
  requirements:
    block:
      '/framework/thirdparty/jquery/*': true
    before:
      components/jquery/jquery.min.js: true
      components/modernizr/modernizr.js: true
      components/ckeditor/ckeditor.js: true
    after:
      components/lodash/lodash.min.js: true
      components/masonry/masonry.pkgd.js: true
      components/postal.js/lib/postal.js: true
      components/fotorama/fotorama-built.js: true
      components/select2/select2.min.js: true
      components/infinite-ajax-scroll/infinite-ajax-scroll-built.js: true
      components/puleos/object-hash-built.js: true
      js/mosaic.js: true
      js/mosaic.jst: true
      js/components/util/strings.js: true
      js/components/data/data.jquery.js: true
      js/components/messaging/messaging.postal.js: true
      js/components/ui/ias.js: true
      js/components/ui/grid.masonry.js: true
      js/components/ui/endless.js: true
      js/message-bus.js: true
      js/widgets/sidebar.js: true
      js/widgets/expando.js: true
      js/widgets/list.js: true
      js/widgets/tabbar.js: true
      js/widgets/actionmenu.js: true
      js/widgets/select2field.js: true
      js/widgets/ckeditor.js: true
      js/widgets/confirmedpasswordfield.js: true
      js/widgets/postable.js: true
      js/widgets/modal.js: true


